package ch.fhnw.wodss.backend.messaging;

public enum MessageType {
	NEW_USER,
	UPDATED_USER,
	UPDATED_USERS,
	NEW_COMMUNITY,
	UPDATED_COMMUNITY_JOINREQUESTS,
	UPDATED_COMMUNITY,
	DELETED_COMMUNITY,
	UPDATED_MATCH,
	NEW_BET,
	UPDATED_BET
}
